#!/usr/bin/env python3
"""Generate src/contents/ui/lib/PinyinData.js from pypinyin's dictionaries.

The widget cannot pull data at runtime, so the tables are baked into a JS
resource. Two tables are emitted:

  CHARS   readings for U+4E00..U+9FFF in codepoint order, space separated, so a
          lookup is an array index instead of a hash of 21k keys.
  PHRASES words whose reading differs from the naive per-character one, i.e.
          exactly the polyphone cases the per-character table gets wrong.

Run after upgrading pypinyin:  python3 tools/gen-pinyin-data.py
"""

import sys

try:
    from pypinyin import pinyin_dict
    from pypinyin.phrases_dict import phrases_dict
except ImportError:
    sys.exit("pypinyin is required: pip install pypinyin")

BLOCK_START = 0x4E00
BLOCK_END = 0x9FFF
# Longer entries are overwhelmingly chengyu, which cost more than they help in
# song lyrics. Two and three character words carry the common polyphones.
MAX_PHRASE = 3

readings = {cp: value.split(",")[0] for cp, value in pinyin_dict.pinyin_dict.items()}


def naive(word):
    return [readings.get(ord(char), "") for char in word]


chars = "".join(readings.get(cp, "") + " " for cp in range(BLOCK_START, BLOCK_END + 1))

phrases = []
for phrase, entries in sorted(phrases_dict.items()):
    if not 2 <= len(phrase) <= MAX_PHRASE:
        continue
    if len(entries) != len(phrase):
        continue
    if any(not readings.get(ord(char)) for char in phrase):
        continue
    actual = [entry[0] for entry in entries]
    if actual == naive(phrase):
        continue
    phrases.append(phrase + ":" + " ".join(actual))

blob = ";".join(phrases)


def js_string(value):
    """Quote as a JS string literal, escaping only what must be escaped."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

with open("src/contents/ui/lib/PinyinData.js", "w", encoding="utf-8") as out:
    out.write(".pragma library\n\n")
    out.write("// Generated by tools/gen-pinyin-data.py from pypinyin. Do not edit by hand.\n")
    out.write("// CHARS: one reading per codepoint from U+%04X to U+%04X, space separated.\n" % (BLOCK_START, BLOCK_END))
    out.write("// PHRASES: \"word:syllable syllable\" entries, ';' separated, for words the\n")
    out.write("// per-character table would romanize with the wrong reading.\n\n")
    out.write("var BLOCK_START = 0x%04X\n" % BLOCK_START)
    out.write("var BLOCK_END = 0x%04X\n" % BLOCK_END)
    out.write("var MAX_PHRASE = %d\n\n" % MAX_PHRASE)
    out.write("var CHARS = %s\n\n" % js_string(chars))
    out.write("var PHRASES = %s\n" % js_string(blob))

print("chars: %d bytes, phrases: %d entries / %d bytes"
      % (len(chars.encode()), len(phrases), len(blob.encode())))
